### ISSUE TITLE
GRID and FULLGRID

### ISSUE THREAD

**Issue by SilasD** [Baughn/Dwarf-Fortress--libgraphics-#10]
GRID:xx:yy controls both the windowed grid size and the fullscreen grid size.  FULLGRID:xx:yy seems to do nothing.  

This matters when the fullscreen font is different than the windowed font.  I use the curses_640x300.png (8x12) for fullscreen, and a doubled version of that font (16x24) for windowed.  

When I switch to fullscreen mode, the font changes properly, but the screen only shows the same amount that windowed mode would show.  I can then use the mousewheel to zoom, which does increase the number of columns and lines displayed, eventually enough to fill the screen.  

If I do zoom, then switch back to windowed mode, the window is zoomed out quite far.

**Comment by Baughn** [comment]
Should be fixed. Of course, now neither setting does anything at all.
