### ISSUE TITLE
Mouse moving renders symbols artifacted.

### ISSUE THREAD

**Issue by virus-found** [Baughn/Dwarf-Fortress--libgraphics-#12]
commit 1f0219def
MOUSE:YES

STANDARD
No issues.

PARTIAL:x (tried 0,2 and 10)
Whenever I move mouse, all symbols begin to "dance" (become covered with artifacts and flicker). Whenever I stop moving mouse - everything becomes as it was, i.e. okay.

FRAME_BUFFER
Same as partial.

ACCUM_BUFFER
Same as partial, but with additional initial terminal output (once the game starts):
GL error: 1282 in g_src/enabler_sdl.cpp:963
Frame 1 complete
GL error: 1282 in g_src/enabler_sdl.cpp:1182
Frame 2 complete
GL error: 1282 in g_src/enabler_sdl.cpp:1182
Frame 3 complete
GL error: 1282 in g_src/enabler_sdl.cpp:1182
Frame 4 complete
GL error: 1282 in g_src/enabler_sdl.cpp:1182
Frame 5 complete
GL error: 1282 in g_src/enabler_sdl.cpp:1182
GL error: 1282 in g_src/enabler_sdl.cpp:1182
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:963
GL error: 1282 in g_src/enabler_sdl.cpp:1182
GL error: 1282 in g_src/enabler_sdl.cpp:1182
GL error: 1282 in g_src/enabler_sdl.cpp:1182
GL error: 1282 in g_src/enabler_sdl.cpp:1182

VBO
No issues.

**Comment by virus-found** [comment]
Introduced with bc6415246 (A variety of changes to rendering and zoom...).

**Comment by eidalac** [comment]
I noticed the same effect.  When just starting, prior to any zooming, it doesn't happen, but once I zoom it persists even when I reset the zoom level.

**Comment by Baughn** [comment]
Still present in d14. I'm looking at it.

**Comment by Baughn** [comment]
I believe I've fixed it for d17.
