### ISSUE TITLE
Garbled menu text

### ISSUE THREAD

**Issue by HandOfCode** [Baughn/Dwarf-Fortress--libgraphics-#14]
Some of the in-game menus are garbled with the hotkey being wrong in some places, and being in the wrong place in some cases, and both in some instances.

The build menu shows this error.

WinXP SP3 Radeon 800.  Windowed mode.

**Comment by kurokikaze** [comment]
I confirm. Windows XP SP3 Gainward Bliss GeForce 9600 GSO PCX. Fullscreen mode.

**Comment by gabehollombe** [comment]
Confirmed on Mac OS X on a MacBook 2.2ghz Core 2 Duo with the Mayday tileset.

**Comment by WolframH** [comment]
Confirmed on Win XP SP2 GeForce 6600GT Windowed mode.

**Comment by soupcan** [comment]
Confirmed on Arch Linux x64, Intel GMA 965, Core 2 Duo T5750 2.00GHz. All game settings at default, no graphical tiles.

**Comment by Baughn** [comment]
Fixed.

**Comment by kurokikaze** [comment]
Woohoo! :)
