### ISSUE TITLE
White tiles get a purple tint when zooming

### ISSUE THREAD

**Issue by eidalac** [Baughn/Dwarf-Fortress--libgraphics-#17]
After converting my tileset to use alpha channel transparency, I noticed that when I zoom (in or out) any white in tiles becomes a light purple.  Resetting the zoom level with F12 give the correct color again, and no gray area are affected.  Using a backup of the same set before adding the alpha channel does not cause the issue.  The sets are in PNG format.

**Comment by eidalac** [comment]
Ok, seems this was due to how I saved my tileset; I did it so that the parts hidden by the alpha channel were still saved in the image, and the purple tint was due to the magenta background leaking through due to the zoom.  Once I re-saved it without the hidden colors, the tiles zoom in and out without any color issues.

**Comment by Baughn** [comment]
Closed.
