### ISSUE TITLE
Controls broken

### ISSUE THREAD

**Issue by freshprince** [Baughn/Dwarf-Fortress--libgraphics-#18]
Since commit 0d7410ffabc06435d553c29794f9a6979d9bb847 the controls in fortress mode are broken. Pressing Left makes the view go SW. Right -> SO. Up -> NW. Down -> NO. R changes the Layout etc. Controls in the menus work fine. I didn't test adventure mode.

**Comment by Baughn** [comment]
This is due to that commit changing the DF<->libgraphics interface. It will go away with the next release, though I'm wondering if I can work around it.

**Comment by N3X15** [comment]
Confirmed on Ubuntu x86.

**Comment by Baughn** [comment]
Fixed.
