### ISSUE TITLE
Mouse Over Window causes blackout

### ISSUE THREAD

**Issue by FluidMind** [Baughn/Dwarf-Fortress--libgraphics-#21]
The title screen goes black when mousing over the windowed DF while another application is active. The menu will update when you change the active selection, much like partial print mode, even in FRAME_BUFFER print mode. WinXP, 40d14.

**Comment by Baughn** [comment]
Noted. I still have no idea what causes this; it's an old bug.

It does not occur in standard mode, by the way; you may want to take advantage of this.

**Comment by Baughn** [comment]
Fixed.
