### ISSUE TITLE
Embarking In linux on high res monitor crashes DF 40D16 

### ISSUE THREAD

**Issue by MattMcDonald** [Baughn/Dwarf-Fortress--libgraphics-#23]
Embarking with df maximized in windowed mode on a 2048x1152 monitor instantly crashes DF. Once the game has loaded into fortress mode I can maximize the screen and all works well. 

Here is the console output on the crash:

matt@capacitor:~/Desktop/df_linux> ./df
mkdir: cannot create directory `unused_libs': File exists
mv: cannot stat`libs/libSDL_': No such file or directory
Using OpenGL output path with client-side arrays
matt@capacitor:~/Desktop/df_linux> ./df
mkdir: cannot create directory `unused_libs': File exists
mv: cannot stat`libs/libSDL_': No such file or directory
Using OpenGL output path with client-side arrays
Gained focus
./df: line 12: 31927 Segmentation fault      ./dwarfort.exe $*
matt@capacitor:~/Desktop/df_linux>

**Comment by Baughn** [comment]
Should be fixed by now
