### ISSUE TITLE
assertion pixel_width >= ttf_width failed

### ISSUE THREAD

**Issue by bogolt** [Baughn/Dwarf-Fortress--libgraphics-#43]
Running df 0.43.05 on osx with retina display. I scolled to make text bigger and df aborted.

````
New window size: 1436x855
Font size: 8x12
Resizing font to 8x12

Resizing font to 8x12
Resizing font to 8x12
Resizing font to 7x10
Resizing font to 6x10
Resizing font to 7x10
Resizing font to 8x12
Resizing font to 8x12
Resizing font to 8x13
Resizing font to 9x13
Resizing font to 10x15
Resizing font to 10x16
Assertion failed: (pixel_width >= ttf_width), function get_handle, file src/g_src/ttf_manager.cpp, line 139.
````

**Comment by lethosor** [comment]
Bugs should generally be reported on the DF issue tracker - this one already is ([5819](http://www.bay12games.com/dwarves/mantisbt/view.php?id=5819)).

**Comment by bogolt** [comment]
sorry, closing it then.

**Comment by Baughn** [comment]
Also I haven't worked on this in ages. I should probably delete the repo, to minimize confusion.

**Comment by rofl0r** [comment]
i doubt deleting the repo would be a good idea, since that would make all the forks parentless (for example mine which is more or less maintained: http://github.com/rofl0r/df-libgraphics )
it would be preferable if you just modify the readme to point out the fact that you're no longer maintaining this.

**Comment by lethosor** [comment]
You could also add a "[Contributing](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)" file, which would display a banner when opening an issue/PR, or maybe an issue/PR template too. It's also possible to disable the issue tracker, although I don't know what that would do to existing issues, and it wouldn't stop PRs.
