### ISSUE TITLE
Working link for the description of repository

### ISSUE THREAD

**Issue by mikebdp2** [Baughn/Dwarf-Fortress--libgraphics-#45]
Hi @Baughn , at the description of your repository " The graphics segment of Dwarf Fortress ... " there is a link " http://www.bay12games.com/forum/index.php?topic=28841. " which doesn't work anymore:

> Not Found
> The requested document was not found on this server.
> 
> Web Server at bay12games.com 

But I discovered a way to fix it! Please replace it with
http://www.bay12forums.com/smf/index.php?topic=28841.0
at least for the archival purposes. Thank you

**Comment by rofl0r** [comment]
btw you should use my fork https://github.com/rofl0r/df-libgraphics it's half-ways recent and has a ton of fixes, this repo here is abandoned

**Comment by Baughn** [comment]
This repo is quite abandoned. Do as he says.
