### ISSUE TITLE
Error launching df-40d13-head linux version

### ISSUE THREAD

**Issue by sawtooth-zz** [Baughn/Dwarf-Fortress--libgraphics-#6]
Files and folders in the archive were dated 08 July 2009 08:02.

I get this error when trying to start Dwarf Fortress using the df script:

./dwarfort.exe: ./libs/libstdc++.so.6: version `GLIBCXX_3.4.11' not found (required by ./libs/libgraphics.so)

The unmodified 40d13 version launched ok on my system.

**Comment by sawtooth-zz** [comment]
OK, it looks like this latest update may have been compiled with a newer gcc version 4.4 which isn't installed yet on my ubuntu system.  I guess whatever system that got used for development must have updated recently. :)

Upgrading with a gcc-4.4 package worked (it updates libstdc6++.so.6) however, that package isn't generally available in Ubuntu without using a custom repository.

**Comment by Baughn** [comment]
This is true.
