### ISSUE TITLE
KEY_HOLD_MS, KEY_REPEAT_MS

### ISSUE THREAD

**Issue by SilasD** [Baughn/Dwarf-Fortress--libgraphics-#9]
.40d13 on Windows.  ATI Radeon 4870, Feb 2009 drivers.  Standard American querty keyboard.

KEY_HOLD_MS doesn't seem to have any effect.

KEY_REPEAT_MS seems to control the initial delay, like KEY_HOLD_MS is supposed to.

Nothing seems to control the actual held-key repeat rate that KEY_REPEAT_MS is supposed to control.  It seems to use the hardcoded (init.h) 150ms value.

**Comment by Baughn** [comment]
Is this still the case in d14?
